### ISSUE TITLE
webpack@5.0.0-beta.29 Cannot find module 'webpack/lib/dependencies/SingleEntryDependency'

### ISSUE THREAD

**Issue by Linkontoask** [ryanclark/karma-webpack#445] opened 2020-09-04 03:43 UTC
- Operating System:
- Node Version: 12.16.1
- NPM Version:
- webpack Version: 5.0.0-beta.29
- karma-webpack Version: 5.2.1

### Expected Behavior

Compile normally

### Actual Behavior

`Cannot find module 'webpack/lib/dependencies/SingleEntryDependency'`

**Comment by samal-rasmussen** [comment] 2020-11-05 15:42
This is a duplicate of #431. I've added a workaround into the comments there.

**Comment by codymikol** [comment] 2021-02-01 02:03
To limit confusion, I am combining all threads for webpack 5 / karma6 support over here ==> https://github.com/ryanclark/karma-webpack/issues/475

**Closed by codymikol** 2021-02-01 02:03 UTC
